import type { Metadata } from "next";
import Link from "next/link";
import { ServiceAreaIcon } from "@/components/public/service-area-icon";
import { getPublicServiceAreas, getPublicServicesByArea, serviceAreaHref } from "@/lib/supabase/services";
export const metadata: Metadata = { title: "Servicios | Conectar Servicios", description: "Soluciones de conectividad, seguridad, infraestructura y tecnología para hogares, empresas y organizaciones." };
export default async function ServicesCatalogPage() {
  const areasResult = await getPublicServiceAreas();
  const groups = await Promise.all(areasResult.data.map(async (area) => ({ area, services: (await getPublicServicesByArea(area.id)).data })));
  return <main className="bg-slate-50"><section className="bg-[#0b2440] py-20 text-white sm:py-28"><div className="public-container"><p className="text-sm font-bold tracking-[.22em] text-orange-400 uppercase">Servicios</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">Soluciones para hogares, empresas y organizaciones</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-blue-100">Conectar Servicios ofrece soluciones de conectividad, seguridad, infraestructura y tecnología para acompañar distintas necesidades.</p></div></section><section className="public-container py-16 sm:py-24" aria-label="Áreas de servicio">{areasResult.unavailable ? <p className="public-empty-state">El catálogo no está disponible temporalmente.</p> : <div className="grid gap-7 lg:grid-cols-2">{groups.map(({ area, services }) => <article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9" key={area.id}><ServiceAreaIcon icon={area.icon} /><h2 className="mt-6 text-3xl font-black text-slate-950">{area.name}</h2><p className="mt-3 leading-7 text-slate-600">{area.short_description}</p>{services.length > 0 && <ul className="mt-6 grid gap-2 border-t border-slate-100 pt-5 sm:grid-cols-2">{services.slice(0, 4).map((service) => <li className="flex gap-2 text-sm font-semibold text-slate-700" key={service.id}><span aria-hidden="true" className="text-orange-600">•</span>{service.name}</li>)}</ul>}<Link className="mt-7 inline-flex rounded-xl bg-blue-950 px-5 py-3 font-bold text-white hover:bg-blue-900" href={serviceAreaHref(area)}>Ver todos los servicios</Link></article>)}</div>}</section></main>;
}
