import { SERVICE_MEDIA_TYPES, SERVICE_OPTION_MODES, type ServiceMediaType, type ServiceOptionMode } from "@/types/services";
export const SERVICE_MEDIA_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"];
export const SERVICE_MEDIA_MAX_BYTES = 5 * 1024 * 1024;
const integer = (value: FormDataEntryValue | null) => Number(String(value ?? ""));
export function validateServiceImage(file: File) { if (!file.size) return; if (!SERVICE_MEDIA_MIME_TYPES.includes(file.type)) return "Usá una imagen JPG, PNG o WebP."; if (file.size > SERVICE_MEDIA_MAX_BYTES) return "La imagen no puede superar los 5 MB."; }
export function parseServiceOption(formData: FormData) {
  const title=String(formData.get("title")??"").trim(), mode=String(formData.get("mode")??""), rawEquipment=String(formData.get("equipment_count")??"").trim(), price=Number(String(formData.get("price")??"")), display_order=integer(formData.get("display_order")); const errors: Record<string,string>={};
  if(!title) errors.title="Ingresá un título."; if(!SERVICE_OPTION_MODES.includes(mode as ServiceOptionMode)) errors.mode="Elegí una modalidad válida."; if(!Number.isFinite(price)||price<0) errors.price="Ingresá un precio válido."; if(!Number.isInteger(display_order)||display_order<0) errors.display_order="Ingresá un orden válido."; const equipment_count=rawEquipment ? Number(rawEquipment) : null; if(equipment_count!==null&&(!Number.isInteger(equipment_count)||equipment_count<1)) errors.equipment_count="Ingresá una cantidad mayor a cero.";
  return Object.keys(errors).length ? {errors} : {errors,data:{title,mode:mode as ServiceOptionMode,equipment_count,price,price_label:String(formData.get("price_label")??"").trim()||null,description:String(formData.get("description")??"").trim()||null,display_order,active:formData.get("active")==="on"}};
}
export function parseServiceMedia(formData: FormData) { const type=String(formData.get("type")??""); const display_order=integer(formData.get("display_order")); const errors:Record<string,string>={}; if(!SERVICE_MEDIA_TYPES.includes(type as ServiceMediaType)) errors.type="Elegí un tipo válido."; if(!Number.isInteger(display_order)||display_order<0) errors.display_order="Ingresá un orden válido."; return Object.keys(errors).length?{errors}:{errors,data:{type:type as ServiceMediaType,alt_text:String(formData.get("alt_text")??"").trim()||null,caption:String(formData.get("caption")??"").trim()||null,display_order,active:formData.get("active")==="on"}}; }
