"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { SERVICE_MEDIA_BUCKET } from "@/lib/supabase/services";
import { parseServiceMedia, parseServiceOption, validateServiceImage } from "@/lib/validations/service-content";
import type { ServiceActionState } from "@/types/services";
async function authorized(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data:p}=await supabase.from("profiles").select("active,role").eq("id",user.id).maybeSingle();return p?.active&&["editor","admin","super_admin"].includes(p.role)?supabase:null;}
function refresh(serviceId:string){revalidatePath("/");revalidatePath("/servicios");revalidatePath("/admin/services");revalidatePath(`/admin/services/${serviceId}/content`);}
export async function saveServiceOption(_:ServiceActionState,formData:FormData):Promise<ServiceActionState>{const parsed=parseServiceOption(formData);if(!parsed.data)return{message:"Revisá los campos marcados.",fieldErrors:parsed.errors};const supabase=await authorized(),serviceId=String(formData.get("service_id")??""),id=String(formData.get("id")??"");if(!supabase||!serviceId)return{message:"No tenés permiso para realizar esta acción."};const result=id?await supabase.from("service_options").update(parsed.data).eq("id",id).eq("service_id",serviceId).select("id").maybeSingle():await supabase.from("service_options").insert({...parsed.data,service_id:serviceId}).select("id").single();if(result.error||!result.data)return{message:"No pudimos guardar la opción comercial."};refresh(serviceId);redirect(`/admin/services/${serviceId}/content?success=option-saved`);}
export async function deleteServiceOption(formData:FormData){const serviceId=String(formData.get("service_id")??""),id=String(formData.get("id")??""),supabase=await authorized();if(!supabase||!serviceId||!id)redirect("/admin/services?error=permission");const {data}=await supabase.from("service_options").delete().eq("id",id).eq("service_id",serviceId).select("id").maybeSingle();if(!data)redirect(`/admin/services/${serviceId}/content?error=permission`);refresh(serviceId);redirect(`/admin/services/${serviceId}/content?success=option-deleted`);}
function pathFor(serviceId:string,file:File){const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";return `${serviceId}/${randomUUID()}.${ext}`;}
export async function saveServiceMedia(_:ServiceActionState,formData:FormData):Promise<ServiceActionState>{const parsed=parseServiceMedia(formData),serviceId=String(formData.get("service_id")??""),id=String(formData.get("id")??"");const value=formData.get("image"),file=value instanceof File?value:new File([],"");const fileError=validateServiceImage(file);if(fileError)parsed.errors.image=fileError;if(!id&&!file.size)parsed.errors.image="Seleccioná una imagen.";if(!parsed.data||Object.keys(parsed.errors).length)return{message:"Revisá los campos marcados.",fieldErrors:parsed.errors};const supabase=await authorized();if(!supabase||!serviceId)return{message:"No tenés permiso para realizar esta acción."};const {data:current}=id?await supabase.from("service_media").select("image_path").eq("id",id).eq("service_id",serviceId).maybeSingle():{data:null};if(id&&!current)return{message:"El medio no existe o no tenés permiso."};let uploaded:string|null=null;if(file.size){uploaded=pathFor(serviceId,file);const {error}=await supabase.storage.from(SERVICE_MEDIA_BUCKET).upload(uploaded,file,{contentType:file.type,cacheControl:"31536000",upsert:false});if(error)return{message:"No pudimos subir la imagen."};}const imagePath=uploaded??current?.image_path;if(!imagePath)return{message:"Seleccioná una imagen."};const {data,error}=await supabase.rpc("save_service_media",{p_id:id||null,p_service_id:serviceId,p_type:parsed.data.type,p_image_path:imagePath,p_alt_text:parsed.data.alt_text,p_caption:parsed.data.caption,p_active:parsed.data.active,p_display_order:parsed.data.display_order});if(error||!data){console.error("Unable to persist service media through RPC",{code:error?.code,message:error?.message,details:error?.details,hint:error?.hint});if(uploaded)await supabase.storage.from(SERVICE_MEDIA_BUCKET).remove([uploaded]);return{message:"No pudimos guardar el medio."};}if(uploaded&&current?.image_path)await supabase.storage.from(SERVICE_MEDIA_BUCKET).remove([current.image_path]);refresh(serviceId);redirect(`/admin/services/${serviceId}/content?success=media-saved`);}
export async function deleteServiceMedia(formData:FormData){const serviceId=String(formData.get("service_id")??""),id=String(formData.get("id")??""),supabase=await authorized();if(!supabase||!serviceId||!id)redirect("/admin/services?error=permission");const {data:item}=await supabase.from("service_media").select("image_path").eq("id",id).eq("service_id",serviceId).maybeSingle();if(!item)redirect(`/admin/services/${serviceId}/content?error=permission`);const {data}=await supabase.from("service_media").delete().eq("id",id).eq("service_id",serviceId).select("id").maybeSingle();if(!data)redirect(`/admin/services/${serviceId}/content?error=permission`);await supabase.storage.from(SERVICE_MEDIA_BUCKET).remove([item.image_path]);refresh(serviceId);redirect(`/admin/services/${serviceId}/content?success=media-deleted`);}
