import Link from "next/link";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { ServiceProjectActionsMenu } from "@/components/admin/services/service-project-actions-menu";
import { createClient } from "@/lib/supabase/server";
import type { ServiceProject } from "@/types/service-projects";

const feedback: Record<string, string> = { created: "El proyecto se creó correctamente.", updated: "El proyecto se actualizó correctamente.", activated: "El proyecto quedó activo.", deactivated: "El proyecto quedó inactivo.", featured: "El proyecto quedó destacado.", unfeatured: "Se quitó el destacado.", deleted: "El proyecto se eliminó correctamente." };
export default async function ServiceProjectsPage({ searchParams }: Readonly<{ searchParams: Promise<{ success?: string; error?: string }> }>) {
  const query = await searchParams; const supabase = await createClient();
  const { data, error } = await supabase.from("service_projects").select("id, service_area_id, service_id, title, slug, project_type, short_description, description, image_path, public_url, featured, active, display_order, service_areas(id, name, slug, icon), services(id, name)").order("display_order").order("title");
  if (error) console.error("Unable to list service projects", error); const projects = (data ?? []) as unknown as ServiceProject[];
  return <><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><AdminPageHeader description="Gestioná trabajos, implementaciones y soluciones realizadas." title="Proyectos / soluciones"/><Link className="rounded-xl bg-orange-600 px-5 py-3 text-center font-bold text-white" href="/admin/services/projects/new">Nuevo proyecto</Link></div>
    {query.success && feedback[query.success] && <p className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{feedback[query.success]}</p>}
    {query.error && <p className={`mb-5 rounded-xl border px-4 py-3 text-sm ${query.error === "image-cleanup" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-red-200 bg-red-50 text-red-800"}`} role="alert">{query.error === "image-cleanup" ? "Los cambios se guardaron, pero no pudimos limpiar la imagen anterior. Podés continuar trabajando normalmente." : query.error === "permission" ? "No tenés permiso para realizar esa acción." : "No pudimos completar la acción. Intentá nuevamente."}</p>}
    {error ? <div className="rounded-2xl border border-red-200 bg-white p-8 text-center">No pudimos cargar los proyectos.</div> : projects.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">Todavía no hay proyectos cargados.</h2><p className="mt-2 text-slate-600">Cargalos desde el admin cuando la información esté validada.</p><Link className="mt-6 inline-block rounded-xl bg-orange-600 px-5 py-3 font-bold text-white" href="/admin/services/projects/new">Crear primer proyecto</Link></div> : <div className="grid gap-4 xl:block xl:rounded-2xl xl:border xl:border-slate-200 xl:bg-white xl:shadow-sm"><div className="hidden grid-cols-[1.2fr_.9fr_.9fr_.7fr_.55fr_.55fr_.35fr_1.1fr] gap-3 border-b border-slate-200 bg-slate-50 px-5 py-3 text-xs font-bold uppercase xl:grid"><span>Proyecto / solución</span><span>Área</span><span>Servicio relacionado</span><span>Tipo</span><span>Estado</span><span>Destacado</span><span>Orden</span><span>Acciones</span></div>{projects.map((project) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:grid xl:grid-cols-[1.2fr_.9fr_.9fr_.7fr_.55fr_.55fr_.35fr_1.1fr] xl:items-center xl:gap-3 xl:rounded-none xl:border-0 xl:border-b xl:shadow-none last:xl:border-b-0" key={project.id}><h2 className="font-bold">{project.title}</h2><p className="mt-2 text-sm xl:mt-0"><b className="xl:hidden">Área: </b>{project.service_areas?.name ?? "—"}</p><p className="mt-2 text-sm xl:mt-0"><b className="xl:hidden">Servicio: </b>{project.services?.name ?? "Sin servicio específico"}</p><p className="mt-2 text-sm xl:mt-0"><b className="xl:hidden">Tipo: </b>{project.project_type ?? "—"}</p><span className={`mt-3 w-fit rounded-full px-2.5 py-1 text-xs font-bold xl:mt-0 ${project.active ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{project.active ? "Activo" : "Inactivo"}</span><p className="mt-2 text-sm xl:mt-0"><b className="xl:hidden">Destacado: </b>{project.featured ? "Sí" : "No"}</p><p className="mt-2 text-sm xl:mt-0"><b className="xl:hidden">Orden: </b>{project.display_order}</p><div className="mt-5 flex gap-2 text-sm xl:mt-0"><Link className="rounded-lg border border-orange-200 bg-orange-50 px-3 py-2 font-bold text-orange-800" href={`/admin/services/projects/${project.id}/edit`}>Editar</Link><ServiceProjectActionsMenu active={project.active} featured={project.featured} id={project.id} title={project.title}/></div></article>)}</div>}
  </>;
}
