import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { cache } from "react";
import { NEWS_BUCKET } from "@/lib/supabase/news";
import { createClient } from "@/lib/supabase/server";
import type { NewsItem } from "@/types/news";
import { argentinaDateFormatter } from "@/lib/utils/news-dates";
const load = cache(async (slug:string) => { const supabase=await createClient(); const { data,error }=await supabase.from("news").select("id,title,slug,excerpt,content,cover_image,category,status,featured,published_at,author_id,created_at").eq("slug",slug).eq("status","published").lte("published_at",new Date().toISOString()).maybeSingle(); if(error){ console.error("Unable to load public news detail",error); return null; } return data as NewsItem|null; });
function imageUrl(path:string|null){ if(!path)return null; const url=process.env.NEXT_PUBLIC_SUPABASE_URL; return url ? `${url}/storage/v1/object/public/${NEWS_BUCKET}/${path.split("/").map(encodeURIComponent).join("/")}` : null; }
export async function generateMetadata({ params }: Readonly<{params:Promise<{slug:string}>}>):Promise<Metadata>{ const {slug}=await params; const item=await load(slug); if(!item)return {title:"Noticia no encontrada"}; const image=imageUrl(item.cover_image); return {title:`${item.title} | Conectar Servicios`,description:item.excerpt ?? item.title,openGraph:{title:item.title,description:item.excerpt ?? item.title,type:"article",publishedTime:item.published_at ?? undefined,images:image?[{url:image}]:undefined}}; }
export default async function NewsDetail({params}:Readonly<{params:Promise<{slug:string}>}>){const {slug}=await params;const item=await load(slug);if(!item)notFound();const image=imageUrl(item.cover_image);return <main className="bg-slate-50 py-12 sm:py-20"><article className="public-container max-w-4xl"><Link className="font-bold text-orange-700" href="/noticias">← Volver a Noticias</Link><header className="mt-8"><p className="public-eyebrow">{item.category}</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">{item.title}</h1>{item.published_at&&<time className="mt-5 block text-slate-500" dateTime={item.published_at}>{argentinaDateFormatter.format(new Date(item.published_at))}</time>}{item.excerpt&&<p className="mt-7 text-xl leading-8 text-slate-600">{item.excerpt}</p>}</header>{image&&<div className="relative mt-10 aspect-[16/9] overflow-hidden rounded-3xl bg-slate-200"><Image alt={`Portada de ${item.title}`} className="object-cover" fill priority sizes="(max-width: 896px) 100vw, 896px" src={image}/></div>}<div className="mt-10 whitespace-pre-wrap text-lg leading-8 text-slate-700">{item.content}</div></article></main>;}
