"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { parsePlayFaq, parsePlayPack, parsePlayPlan, parsePlaySettings } from "@/lib/validations/conectar-play";
import type { ConectarPlayActionState } from "@/types/conectar-play";

type PlayTable = "conectar_play_plans" | "conectar_play_packs" | "conectar_play_faqs";
async function authorized(roles = ["editor", "admin", "super_admin"]) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data, error } = await supabase.from("profiles").select("active, role").eq("id", user.id).maybeSingle(); if (error) console.error("Unable to authorize Conectar Play operation", error); return data?.active && roles.includes(data.role) ? supabase : null; }
const failure = (error: { code?: string } | null) => error?.code === "23505" ? "Ya existe un registro con ese slug." : error?.code === "42501" ? "No tenés permiso para realizar esta acción." : "No pudimos guardar los cambios. Intentá nuevamente.";
function refresh() { revalidatePath("/"); revalidatePath("/conectar-play"); revalidatePath("/admin/conectar-play"); }

export async function savePlaySettings(_state: ConectarPlayActionState, form: FormData): Promise<ConectarPlayActionState> { const parsed = parsePlaySettings(form); if (!parsed.data) return { message: "Revisá los campos marcados.", fieldErrors: parsed.errors }; const supabase = await authorized(["admin", "super_admin"]); if (!supabase) return { message: "No tenés permiso para modificar la configuración." }; const id = String(form.get("id") ?? ""); const result = id ? await supabase.from("conectar_play_settings").update(parsed.data).eq("id", id).select("id").maybeSingle() : await supabase.from("conectar_play_settings").insert(parsed.data).select("id").single(); if (result.error || !result.data) { console.error("Unable to save Conectar Play settings", result.error); return { message: failure(result.error) }; } refresh(); return { success: true, message: "Configuración guardada correctamente." }; }

export async function savePlayPlan(_state: ConectarPlayActionState, form: FormData): Promise<ConectarPlayActionState> { const parsed = parsePlayPlan(form); if (!parsed.data) return { message: "Revisá los campos marcados.", fieldErrors: parsed.errors }; return persist("conectar_play_plans", parsed.data, form); }
export async function savePlayPack(_state: ConectarPlayActionState, form: FormData): Promise<ConectarPlayActionState> { const parsed = parsePlayPack(form); if (!parsed.data) return { message: "Revisá los campos marcados.", fieldErrors: parsed.errors }; return persist("conectar_play_packs", parsed.data, form); }
export async function savePlayFaq(_state: ConectarPlayActionState, form: FormData): Promise<ConectarPlayActionState> { const parsed = parsePlayFaq(form); if (!parsed.data) return { message: "Revisá los campos marcados.", fieldErrors: parsed.errors }; return persist("conectar_play_faqs", parsed.data, form); }
async function persist(table: PlayTable, data: object, form: FormData): Promise<ConectarPlayActionState> { const supabase = await authorized(); if (!supabase) return { message: "No tenés permiso para realizar esta acción." }; const id = String(form.get("id") ?? ""); const result = id ? await supabase.from(table).update(data).eq("id", id).select("id").maybeSingle() : await supabase.from(table).insert(data).select("id").single(); if (result.error || !result.data) { console.error(`Unable to save ${table}`, result.error); return { message: failure(result.error) }; } refresh(); redirect("/admin/conectar-play?success=saved"); }

export async function deletePlayItem(form: FormData) { const table = String(form.get("table") ?? "") as PlayTable; const allowed: PlayTable[] = ["conectar_play_plans", "conectar_play_packs", "conectar_play_faqs"]; const id = String(form.get("id") ?? ""); const supabase = await authorized(); if (!allowed.includes(table) || !id || !supabase) redirect("/admin/conectar-play?error=permission"); const { data, error } = await supabase.from(table).delete().eq("id", id).select("id").maybeSingle(); if (error || !data) { console.error(`Unable to delete ${table}`, error); redirect("/admin/conectar-play?error=unexpected"); } refresh(); redirect("/admin/conectar-play?success=deleted"); }
