"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { EVENTS_BUCKET } from "@/lib/supabase/events";
import { createClient } from "@/lib/supabase/server";
import { parseEventForm, validateEventImage } from "@/lib/validations/events";
import type { EventActionState, EventStatus } from "@/types/events";
async function authorized(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data:p}=await supabase.from("profiles").select("active,role").eq("id",user.id).maybeSingle();return p?.active&&["editor","admin","super_admin"].includes(p.role)?supabase:null;}
function refresh(...slugs:(string|undefined)[]){revalidatePath("/");revalidatePath("/eventos");revalidatePath("/admin/events");for(const slug of slugs)if(slug)revalidatePath(`/eventos/${slug}`);}
function path(file:File){const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";return `${new Date().toISOString().slice(0,10)}/${randomUUID()}.${ext}`;}
export async function saveEvent(_:EventActionState,form:FormData):Promise<EventActionState>{const parsed=parseEventForm(form),id=String(form.get("id")??""),value=form.get("image"),file=value instanceof File?value:new File([],"");const imageError=validateEventImage(file);if(imageError)parsed.errors.image=imageError;if(!parsed.data||Object.keys(parsed.errors).length)return {message:"Revisá los campos marcados.",fieldErrors:parsed.errors};const supabase=await authorized();if(!supabase)return {message:"No tenés permiso para realizar esta acción."};let previousImage:string|null=null,previousSlug="";if(id){const {data,error}=await supabase.from("events").select("image_path,slug").eq("id",id).maybeSingle();if(error||!data)return {message:"No pudimos encontrar el evento."};previousImage=data.image_path;previousSlug=data.slug;}let uploaded:string|null=null;if(file.size){uploaded=path(file);const {error}=await supabase.storage.from(EVENTS_BUCKET).upload(uploaded,file,{contentType:file.type,cacheControl:"31536000"});if(error)return {message:"No pudimos subir la imagen."};}const values={...parsed.data,image_path:uploaded??previousImage};const result=id?await supabase.from("events").update(values).eq("id",id).select("id").maybeSingle():await supabase.from("events").insert(values).select("id").single();if(result.error||!result.data){if(uploaded)await supabase.storage.from(EVENTS_BUCKET).remove([uploaded]);return {message:result.error?.code==="23505"?"Ese slug ya está en uso.":"No pudimos guardar el evento.",fieldErrors:result.error?.code==="23505"?{slug:"Este slug ya existe."}:undefined};}let cleanup=false;if(uploaded&&previousImage&&!/^https?:\/\//.test(previousImage))cleanup=Boolean((await supabase.storage.from(EVENTS_BUCKET).remove([previousImage])).error);refresh(parsed.data.slug,previousSlug);redirect(`/admin/events?success=${id?"updated":"created"}${cleanup?"&error=image-cleanup":""}`);}
export async function updateEventStatus(form:FormData){const id=String(form.get("id")??""),status=String(form.get("status")??"") as EventStatus,supabase=await authorized();if(!supabase||!id||!["draft","published","archived"].includes(status))redirect("/admin/events?error=permission");const {data,error}=await supabase.from("events").update({status}).eq("id",id).select("slug").maybeSingle();if(error||!data)redirect("/admin/events?error=permission");refresh(data.slug);redirect(`/admin/events?success=${status}`);}
export async function toggleEventFeatured(form:FormData){const id=String(form.get("id")??""),featured=form.get("featured")==="true",supabase=await authorized();if(!supabase||!id)redirect("/admin/events?error=permission");const {data,error}=await supabase.from("events").update({featured}).eq("id",id).select("slug").maybeSingle();if(error||!data)redirect("/admin/events?error=permission");refresh(data.slug);redirect(`/admin/events?success=${featured?"featured":"unfeatured"}`);}
export async function deleteEvent(form:FormData){const id=String(form.get("id")??""),supabase=await authorized();if(!supabase||!id)redirect("/admin/events?error=permission");const {data:item}=await supabase.from("events").select("slug,image_path").eq("id",id).maybeSingle();const {data,error}=await supabase.from("events").delete().eq("id",id).select("id").maybeSingle();if(error||!data)redirect("/admin/events?error=permission");let cleanup=false;if(item?.image_path&&!/^https?:\/\//.test(item.image_path))cleanup=Boolean((await supabase.storage.from(EVENTS_BUCKET).remove([item.image_path])).error);refresh(item?.slug);redirect(`/admin/events?success=deleted${cleanup?"&error=image-cleanup":""}`);}
