"use client";

import { useActionState } from "react";
import { savePlayFaq, savePlayPack, savePlayPlan, savePlaySettings } from "@/app/admin/conectar-play/actions";
import type { ConectarPlayActionState, ConectarPlayFaq, ConectarPlayPack, ConectarPlayPlan, ConectarPlaySettings } from "@/types/conectar-play";

const input = "mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-slate-950 outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200";
const initial: ConectarPlayActionState = {};
function Feedback({ state }: { state: ConectarPlayActionState }) { return state.message ? <p className={`rounded-xl border px-4 py-3 text-sm ${state.success ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`} role={state.success ? "status" : "alert"}>{state.message}</p> : null; }
function ErrorText({ state, name }: { state: ConectarPlayActionState; name: string }) { return state.fieldErrors?.[name] ? <span className="mt-1 block text-xs text-red-700">{state.fieldErrors[name]}</span> : null; }
const Check = ({ name, label, value = true }: { name: string; label: string; value?: boolean }) => <label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input defaultChecked={value} name={name} type="checkbox" />{label}</label>;
const Field = ({ label, name, state, ...props }: { label: string; name: string; state: ConectarPlayActionState } & React.InputHTMLAttributes<HTMLInputElement>) => <label className="block text-sm font-semibold text-slate-700">{label}<input className={input} id={name} name={name} {...props} /><ErrorText name={name} state={state} /></label>;
const Textarea = ({ label, name, value }: { label: string; name: string; value?: string | null }) => <label className="block text-sm font-semibold text-slate-700">{label}<textarea className={`${input} min-h-24`} defaultValue={value ?? ""} name={name} /></label>;

export function SettingsForm({ value, canManage }: { value: ConectarPlaySettings | null; canManage: boolean }) { const [state, action, pending] = useActionState(savePlaySettings, initial); if (!canManage) return <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Solo administradores y super administradores pueden modificar esta sección.</p>; return <form action={action} className="grid gap-4 md:grid-cols-2">{value && <input name="id" type="hidden" value={value.id} />}<Check label="Módulo activo" name="active" value={value?.active} /><Check label="Mostrar Stick" name="onn_enabled" value={value?.onn_enabled} /><Field defaultValue={value?.channel_count} label="Cantidad de canales" min="1" name="channel_count" required state={state} type="number" /><Field defaultValue={value?.simultaneous_devices} label="Dispositivos simultáneos" min="1" name="simultaneous_devices" required state={state} type="number" /><Field defaultValue={value?.web_url ?? ""} label="URL para ver desde navegador" name="web_url" state={state} type="url" /><Field defaultValue={value?.onn_sale_price ?? ""} label="Precio de venta Stick (opcional)" min="0" name="onn_sale_price" state={state} step="0.01" type="number" /><Field defaultValue={value?.onn_rental_price ?? ""} label="Precio mensual de alquiler Stick (opcional)" min="0" name="onn_rental_price" state={state} step="0.01" type="number" /><div className="md:col-span-2"><Textarea label="Descripción corta" name="short_description" value={value?.short_description} /></div><Textarea label="Texto de compatibilidad" name="compatibility_text" value={value?.compatibility_text} /><Textarea label="Texto sobre TV no compatibles" name="incompatible_tv_text" value={value?.incompatible_tv_text} /><Textarea label="Descripción Stick" name="onn_description" value={value?.onn_description} /><Textarea label="Texto de soporte" name="support_text" value={value?.support_text} /><div className="md:col-span-2"><Feedback state={state} /><button className="mt-4 rounded-xl bg-orange-600 px-5 py-2.5 font-bold text-white disabled:opacity-50" disabled={pending}>{pending ? "Guardando…" : "Guardar configuración"}</button></div></form>; }

export function PlanForm({ value }: { value?: ConectarPlayPlan }) { const [state, action, pending] = useActionState(savePlayPlan, initial); return <form action={action} className="grid gap-3 md:grid-cols-2">{value && <input name="id" type="hidden" value={value.id} />}<Field defaultValue={value?.name} label="Nombre" name="name" required state={state} /><Field defaultValue={value?.slug} label="Slug" name="slug" required state={state} /><Textarea label="Descripción" name="description" value={value?.description} /><div className="space-y-3"><Field defaultValue={value?.promotional_price} label="Precio promocional" min="0" name="promotional_price" required state={state} step="0.01" type="number" /><Field defaultValue={value?.promotion_label ?? ""} label="Etiqueta de promoción" name="promotion_label" state={state} /></div><Field defaultValue={value?.promotion_discount_percent ?? ""} label="Porcentaje de descuento" max="100" min="0" name="promotion_discount_percent" state={state} step="0.01" type="number" /><Field defaultValue={value?.promotion_duration_months ?? ""} label="Duración en meses" min="1" name="promotion_duration_months" state={state} type="number" /><Field defaultValue={value?.promotion_start?.slice(0, 16)} label="Inicio promoción" name="promotion_start" state={state} type="datetime-local" /><Field defaultValue={value?.promotion_end?.slice(0, 16)} label="Fin promoción" name="promotion_end" state={state} type="datetime-local" /><Field defaultValue={value?.display_order ?? 0} label="Orden" min="0" name="display_order" required state={state} type="number" /><div className="flex flex-wrap gap-4"><Check label="Pack Fútbol" name="includes_football" value={value?.includes_football} /><Check label="Destacado" name="featured" value={value?.featured} /><Check label="Activo" name="active" value={value?.active} /></div><div className="md:col-span-2"><Feedback state={state} /><button className="mt-3 rounded-xl bg-orange-600 px-5 py-2 font-bold text-white" disabled={pending}>{pending ? "Guardando…" : value ? "Actualizar plan" : "Crear plan"}</button></div></form>; }

export function PackForm({ value }: { value?: ConectarPlayPack }) { const [state, action, pending] = useActionState(savePlayPack, initial); return <form action={action} className="grid gap-3 md:grid-cols-2">{value && <input name="id" type="hidden" value={value.id} />}<Field defaultValue={value?.name} label="Nombre" name="name" required state={state} /><Field defaultValue={value?.price ?? ""} label="Precio opcional" min="0" name="price" state={state} step="0.01" type="number" /><Textarea label="Descripción" name="description" value={value?.description} /><div className="space-y-3"><Field defaultValue={value?.display_order ?? 0} label="Orden" min="0" name="display_order" required state={state} type="number" /><Check label="Activo" name="active" value={value?.active} /></div><div className="md:col-span-2"><Feedback state={state} /><button className="mt-3 rounded-xl bg-orange-600 px-5 py-2 font-bold text-white" disabled={pending}>{pending ? "Guardando…" : value ? "Actualizar pack" : "Crear pack"}</button></div></form>; }

export function FaqForm({ value }: { value?: ConectarPlayFaq }) { const [state, action, pending] = useActionState(savePlayFaq, initial); return <form action={action} className="grid gap-3 md:grid-cols-2">{value && <input name="id" type="hidden" value={value.id} />}<Field defaultValue={value?.question} label="Pregunta" name="question" required state={state} /><Field defaultValue={value?.display_order ?? 0} label="Orden" min="0" name="display_order" required state={state} type="number" /><Textarea label="Respuesta" name="answer" value={value?.answer} /><Check label="Activo" name="active" value={value?.active} /><div className="md:col-span-2"><Feedback state={state} /><button className="mt-3 rounded-xl bg-orange-600 px-5 py-2 font-bold text-white" disabled={pending}>{pending ? "Guardando…" : value ? "Actualizar pregunta" : "Crear pregunta"}</button></div></form>; }
