"use client";
import Image from "next/image";
import Link from "next/link";
import { useActionState, useState } from "react";
import { saveServiceProject } from "@/app/admin/services/projects/actions";
import { normalizeProjectSlug } from "@/lib/validations/service-projects";
import type { ServiceProjectActionState, ServiceProjectFormValues } from "@/types/service-projects";
import type { Service, ServiceArea } from "@/types/services";

const input = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-slate-950 shadow-sm outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200";
type OptionArea = Pick<ServiceArea, "id" | "name">;
type OptionService = Pick<Service, "id" | "name" | "service_area_id">;
export function ServiceProjectForm({ areas, services, id, initialValues, currentImageUrl }: Readonly<{ areas: OptionArea[]; services: OptionService[]; id?: string; initialValues?: ServiceProjectFormValues; currentImageUrl?: string | null }>) {
  const [state, action, pending] = useActionState(saveServiceProject, {} as ServiceProjectActionState);
  const [slug, setSlug] = useState(initialValues?.slug ?? ""); const [manualSlug, setManualSlug] = useState(Boolean(id));
  const [areaId, setAreaId] = useState(initialValues?.service_area_id ?? "");
  const error = (key: string) => state.fieldErrors?.[key];
  const availableServices = services.filter((service) => service.service_area_id === areaId);
  return <form action={action} className="space-y-6">
    {id && <><input name="id" type="hidden" value={id}/><input name="current_image_path" type="hidden" value={initialValues?.image_path ?? ""}/><input name="current_service_area_id" type="hidden" value={initialValues?.service_area_id}/></>}
    {state.message && <p className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{state.message}</p>}
    <fieldset className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><legend className="px-2 text-lg font-bold">Datos principales</legend><div className="grid gap-5 sm:grid-cols-2">
      <label className="text-sm font-semibold">Título *<input className={input} defaultValue={initialValues?.title} name="title" onChange={(e) => { if (!manualSlug) setSlug(normalizeProjectSlug(e.target.value)); }} required/>{error("title") && <span className="text-xs text-red-700">{error("title")}</span>}</label>
      <label className="text-sm font-semibold">Slug *<input className={input} name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" onChange={(e) => { setManualSlug(true); setSlug(e.target.value); }} required value={slug}/>{error("slug") && <span className="text-xs text-red-700">{error("slug")}</span>}</label>
      <label className="text-sm font-semibold">Área de servicio *<select className={input} name="service_area_id" onChange={(e) => setAreaId(e.target.value)} required value={areaId}><option disabled value="">Seleccioná un área</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select>{error("service_area_id") && <span className="text-xs text-red-700">{error("service_area_id")}</span>}</label>
      <label className="text-sm font-semibold">Servicio relacionado <span className="font-normal text-slate-500">(opcional)</span><select className={input} defaultValue={initialValues?.service_id ?? ""} key={areaId} name="service_id"><option value="">Sin servicio específico</option>{availableServices.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select>{error("service_id") && <span className="text-xs text-red-700">{error("service_id")}</span>}</label>
      <label className="text-sm font-semibold sm:col-span-2">Tipo de proyecto/solución <span className="font-normal text-slate-500">(opcional)</span><input className={input} defaultValue={initialValues?.project_type ?? ""} maxLength={80} name="project_type"/>{error("project_type") && <span className="text-xs text-red-700">{error("project_type")}</span>}</label>
    </div></fieldset>
    <fieldset className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><legend className="px-2 text-lg font-bold">Contenido</legend><div className="grid gap-5"><label className="text-sm font-semibold">Descripción corta<textarea className={`${input} min-h-24`} defaultValue={initialValues?.short_description ?? ""} name="short_description"/></label><label className="text-sm font-semibold">Descripción completa<textarea className={`${input} min-h-40`} defaultValue={initialValues?.description ?? ""} name="description"/></label></div></fieldset>
    <fieldset className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><legend className="px-2 text-lg font-bold">Imagen</legend>{currentImageUrl && <div className="relative mb-4 aspect-video max-w-md overflow-hidden rounded-xl bg-slate-100"><Image alt={`Imagen actual de ${initialValues?.title ?? "proyecto"}`} className="object-cover" fill sizes="448px" src={currentImageUrl}/></div>}<label className="text-sm font-semibold">JPG, PNG o WebP (máximo 5 MB)<input accept="image/jpeg,image/png,image/webp" className={input} name="image" type="file"/>{currentImageUrl && <span className="mt-1 block text-xs font-normal text-slate-500">Si no elegís otra imagen, se conservará la actual.</span>}{error("image") && <span className="text-xs text-red-700">{error("image")}</span>}</label></fieldset>
    <fieldset className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><legend className="px-2 text-lg font-bold">Enlace</legend><label className="text-sm font-semibold">URL pública <span className="font-normal text-slate-500">(opcional)</span><input className={input} defaultValue={initialValues?.public_url ?? ""} name="public_url" placeholder="/ruta-interna o https://..."/>{error("public_url") && <span className="text-xs text-red-700">{error("public_url")}</span>}</label></fieldset>
    <fieldset className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><legend className="px-2 text-lg font-bold">Presentación</legend><div className="grid items-end gap-5 sm:grid-cols-3"><label className="text-sm font-semibold">Orden<input className={input} defaultValue={initialValues?.display_order ?? 0} min="0" name="display_order" required step="1" type="number"/>{error("display_order") && <span className="text-xs text-red-700">{error("display_order")}</span>}</label><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input className="size-5 accent-orange-600" defaultChecked={initialValues?.featured} name="featured" type="checkbox"/> Destacado</label><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input className="size-5 accent-orange-600" defaultChecked={initialValues?.active ?? true} name="active" type="checkbox"/> Activo</label></div></fieldset>
    <div className="flex flex-wrap justify-end gap-3"><Link className="rounded-xl border border-slate-300 px-5 py-2.5 font-bold" href="/admin/services/projects">Cancelar</Link><button className="rounded-xl bg-orange-600 px-5 py-2.5 font-bold text-white disabled:opacity-60" disabled={pending}>{pending ? "Guardando…" : "Guardar proyecto"}</button></div>
  </form>;
}
